tangoWithDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tangyDjango/', include('tangyDjango.urls')), # referring to tangyDjango's urls.py to include that application as part of the tangoWithDjango project
    path('register/', user_views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'), #LoginView and LogoutView are class-based views
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

'''
Login and logout are user-specific so the templates should be in the users folder
'''

tangyDjango/urls.py
# Create URL patterns here
from . import views # the dot means same folder
from django.urls import path 
#from .views import HomePageView
app_name = 'tangyDjango'

urlpatterns = [
    path('',views.index, name='index'),
    path('item/', views.item, name='item'),
    path('<int:item_id>/', views.detail, name='detail'), # displaying an integer (the primary key) as the name of the page
    path('add', views.create_item, name='create_item'),
    path('edit/<int:id>/', views.edit_item, name="edit_item"),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

'''
the quotes would be empty for an empty path, index is the name of the path to views.index.
If something was in the quotations it would appear as tangyDjango/something in the localhost
'''

urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tangyDjango/', include('tangyDjango.urls')), # referring to tangyDjango's urls.py to include that application as part of the tangoWithDjango project
    path('register/', user_views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'), #LoginView and LogoutView are class-based views
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

'''
Login and logout are user-specific so the templates should be in the users folder
'''

tangyDjango/models.py
from django.db import models

# Create your models here.

# inheriting the model from the model class

class foodItems(models.Model):
    def __str__(self):
        return self.item_name
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default='https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg')
    

users/models.py
from django.db import models

# Create your models here.

tangyDjango/forms.py
from django import forms 
from .models import foodItems

class ItemForm(forms.ModelForm):
    class Meta:
        model=foodItems
        fields=['item_name','item_desc','item_price','item_image']

    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm): # to have a class inheriting from UserCreationForm
    email = forms.EmailField()
    class Meta(): # meta is data about data, in this case about the registerform class
        model=User
        fields=['username', 'email', 'password1', 'password2']
        

tangyDjango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import foodItems
from django.template import loader
from .forms import ItemForm

# Create your views here.
def index(request):
    item_list=foodItems.objects.all()
    #template=loader.get_template('tangyDjango/index.html')
    context={
    'item_list':item_list
    }
    #return HttpResponse(template.render(context,request))
    return render(request, 'tangyDjango/index.html', context)
    
def Check(request):
    return HttpResponse('Hello Check')

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request, item_id):
    item = foodItems.objects.get(pk = item_id)
    context = {
        'item':item,
    }
    return render(request, 'tangyDjango/detail.html', context)          

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('tangyDjango:index')
    return render(request, 'tangyDjango/item_form.html', {'form':form})      

def edit_item(request, id):
    item = foodItems.objects.get(id=id)   
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('tangyDjango:index')
    return render(request, 'tangyDjango/item_form.html', {'form':form, 'item':item})           

def delete_item(request, id):
    item = foodItems.objects.get(id=id)
    if request.method == "POST":
        item.delete()
        return redirect('tangyDjango:index')
    return render(request, 'tangyDjango/item_delete.html', {'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm


# Create your views here.

def register(request):
    if request.method=='POST': # trying to input data, called once signup is clicked
        form=RegisterForm(request.POST) # request.POST in brackets means data is being sent to the user creation form
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username') # extracts the username from the cleaned data, just form data but all the inputs are separate
            messages.success(request, f'welcome {username}, your account is created')
            return redirect('login')
    else: # called before the if condition
        form = RegisterForm()
        return render(request, 'users/register.html', {'form':form}) # the {{form}} in register.html
            





tangyDjango/templates/tangyDjango/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel = "stylesheet", href="{% static 'tangyDjango/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class = "navbar navbar-dark bg-light">
        <a href = "#" class = "navbar-brand" style = "color:#000000">Super Sausages</a>
        <div class="navbar">
            <a class = "nav-item nav-link" href = "{% url 'tangyDjango:create_item' %}">Add Item</a>
            <a class = "nav-item nav-link" href = "#">&nbsp;&nbsp;Delete Item</a>
            <a class = "nav-item nav-link" href = "#">&nbsp;&nbsp;View Item&nbsp;&nbsp;</a>
            {% if user.is_authenticated %}
                <a class = "nav-item nav-link" href = "{% url 'logout' %}">Logout</a>
            {% else %}
                <a class = "nav-item nav-link" href = "{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class = "alert alert-{{message.tags}}">
            {{message}}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}

    {% endblock %}
</body>
</html>

tangyDjango/templates/tangyDjango/detail.html

{% extends 'tangyDjango/base.html' %}
{% block body %}

<div class = "container">
    <div class = "row">
        <div class = "col-md-6">
            <img src = "{{item.item_image}}", width = "500", height="500", class = "wdn-stretch rounded corners"/>
        </div>
        <div class = "col-md-6">
    <h1>{{item.item_name}}</h1>
    <h2>{{item.item_desc}}</h2>
    <h3>{{item.item_price}}</h3> 
    <a href = {% url 'tangyDjango:delete_item' item.id %}>Delete</a>
        </div> 
    </div>
</div>
{% endblock %}

tangyDjango/templates/tangyDjango/index.html

{% extends 'tangyDjango/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% for item in item_list %}

    <div class = "row">
        <div class = "col-md-3 offset-md-1">
            <img class = "card" height = "150px" width = "500px" src = "{{item.item_image}}">
        </div>
        <div class = "col-md-4 offset-md-2">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>{{item.item_price}}</h3>
        </div>
        <div class = "col-md-2">
            <a href = "{% url 'tangyDjango:detail' item.id %}" class = "btn btn-success">Details</a>
        </div>
    </div>

    {% endfor %}
    {% endblock %}

    <ul>
        <li><a href = "{% url 'tangyDjango:detail' item.id %}">{{item.id}} -- {{item.item_name}}</a></li>
    </ul>

</body>
</html>


tangyDjango/templates/tangyDjango/item_delete.html
<form method = "POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}?</h2>
    <button type = "submit">
        Confirm
    </button>
</form>

tangyDjango/templates/tangyDjango/item_form.html
{% extends 'tangyDjango/base.html' %}
{% block body %}
<form method = "POST">
    {% csrf_token %}
    {{ form }}
    <button type = "submit">
        Save
    </button>
</form>
{% endblock %}

tangyDjango/templates/tangyDjango/templates.html
<h1>Home Page</h1>

users/templates/users/login.html
<form method = 'POST'>
    {% csrf_token %}
    {{form}}
    <button type ="submit">
        Login
    </button>
</form>

users/templates/users/logout.html
<h1>You have been logged out :)</h1>

users/templates/users/register.html
<form method = "POST">
    {% csrf_token %}
    {{form}}
    <button type = "submit">
        Sign Up
    </button>
</form>